### ISSUE TITLE
在线推理端口打不开

### ISSUE THREAD

**Issue by dzysunshine** [FederatedAI/KubeFATE#124]
打开在线推理端口显示如下，{"code":"103","message":"SYSTEM_ERROR"}，是什么原因呢？

**Comment by huangmingkai** [comment]
我遇到了同样的错误信息，出错的原因是文档给的curl命令中的冒号是中文的，改成英文的就过了
我是用docker exec -it serving-9999_serving-proxy_1 sh登录到serving-proxy的docker容器中，然后vi /data/projects/fate/serving-proxy/logs/fate-serving-proxy-error.log看出错信息看出来的

**Comment by dzysunshine** [comment]
> 我遇到了同样的错误信息，出错的原因是文档给的curl命令中的冒号是中文的，改成英文的就过了
> 我是用docker exec -it serving-9999_serving-proxy_1 sh登录到serving-proxy的docker容器中，然后vi /data/projects/fate/serving-proxy/logs/fate-serving-proxy-error.log看出错信息看出来的

感谢你的回复，但是我的curl命令中没有中文冒号呀，可以把你的curl命令发一下吗？我查看了这个log文件，报错如下：2020-04-26 07:22:42,796 [ERROR] c.w.a.f.s.c.r.c.ErrorMessageUtil(ErrorMessageUtil.java:53) - SYSTEM_ERROR
com.alibaba.fastjson.JSONException: syntax error, EOF
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:600) ~[fastjson-1.2.60.jar:?]
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1397) ~[fastjson-1.2.60.jar:?]
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1363) ~[fastjson-1.2.60.jar:?]
        at com.alibaba.fastjson.JSON.parse(JSON.java:170) ~[fastjson-1.2.60.jar:?]
        at com.alibaba.fastjson.JSON.parse(JSON.java:180) ~[fastjson-1.2.60.jar:?]
        at com.alibaba.fastjson.JSON.parse(JSON.java:149) ~[fastjson-1.2.60.jar:?]
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:241) ~[fastjson-1.2.60.jar:?]
        at com.webank.ai.fate.serving.proxy.controller.ProxyController.buildInboundPackageFederation(ProxyController.java:104) ~[fate-serving-proxy-1.2
        at com.webank.ai.fate.serving.proxy.controller.ProxyController.access$000(ProxyController.java:34) ~[fate-serving-proxy-1.2.0.jar:?]
        at com.webank.ai.fate.serving.proxy.controller.ProxyController$1.call(ProxyController.java:79) ~[fate-serving-proxy-1.2.0.jar:?]
        at com.webank.ai.fate.serving.proxy.controller.ProxyController$1.call(ProxyController.java:66) ~[fate-serving-proxy-1.2.0.jar:?]
        at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:328) ~[spring-web-5.2.0.
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_192]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_192]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_192]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_192]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
2020-04-26 07:23:29,503 [ERROR] c.w.a.f.s.c.r.c.ErrorMessageUtil(ErrorMessageUtil.java:53) - SYSTEM_ERROR
org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public java.util.concurrent.Callable<java.lang.St
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethod
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.
        at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:12
        at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:167) ~[spring-web-5.2.0.RE
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134) ~[spring-web-5.2.0.RELEASE.j
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
- /data/projects/fate/serving-proxy/logs/fate-serving-proxy-error.log 1/453 0%

**Comment by dzysunshine** [comment]
感谢帮助，但我最后发现报错原因是我使用的是Xshell，所以在解析json字符串的时候会有问题，最后我是使用了postman工具发送了请求，成功了
![在线推理成功](https://user-images.githubusercontent.com/43950019/80481458-096cc380-8985-11ea-9c18-aabd41218a18.png)

**Comment by LaynePeng** [comment]
Good, close as solved.

**Comment by tdye24** [comment]
我也报类似的错误，即使用postman也不能保证每次都成功，只有很少次数能正确返回
![微信图片_20200818224448](https://user-images.githubusercontent.com/38368472/90528491-4283aa80-e1a5-11ea-8fa9-a366e381644d.png)
