### ISSUE TITLE
提交任务时报错,"description":"Error received from peer"

### ISSUE THREAD

**Issue by learningwang** [FederatedAI/KubeFATE#129]
(venv) [root@1d9ab5e9f7b6 fate_flow]# python fate_flow_client.py -f submit_job -d examples/test_hetero_lr_job_dsl.json -c examples/test_hetero_lr_job_conf.json
{
    "retcode": 100,
    "retmsg": "rpc request error: <_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.INTERNAL\n\tdetails = \"0.0.0.0:9370: java.util.concurrent.TimeoutException: [UNARYCALL][SERVER] unary call server error: overall process time exceeds timeout: 60000, metadata: {\"task\":{\"taskId\":\"202005080940492786716\"},\"src\":{\"name\":\"202005080940492786716\",\"partyId\":\"9999\",\"role\":\"fateflow\",\"callback\":{\"ip\":\"0.0.0.0\",\"port\":9360}},\"dst\":{\"name\":\"202005080940492786716\",\"partyId\":\"10000\",\"role\":\"fateflow\"},\"command\":{\"name\":\"fateflow\"},\"operator\":\"POST\",\"conf\":{\"overallTimeout\":\"60000\"}}, lastPacketTimestamp: 1588930849341, loopEndTimestamp: 1588930909381\n\tat com.webank.ai.fate.networking.proxy.grpc.service.DataTransferPipedServerImpl.unaryCall(DataTransferPipedServerImpl.java:245)\n\tat com.webank.ai.fate.api.networking.proxy.DataTransferServiceGrpc$MethodHandlers.invoke(DataTransferServiceGrpc.java:346)\n\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)\n\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)\n\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)\n\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\n\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n\"\n\tdebug_error_string = \"{\"created\":\"@1588930909.382965656\",\"description\":\"Error received from peer\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1017,\"grpc_message\":\"0.0.0.0:9370: java.util.concurrent.TimeoutException: [UNARYCALL][SERVER] unary call server error: overall process time exceeds timeout: 60000, metadata: {\"task\":{\"taskId\":\"202005080940492786716\"},\"src\":{\"name\":\"202005080940492786716\",\"partyId\":\"9999\",\"role\":\"fateflow\",\"callback\":{\"ip\":\"0.0.0.0\",\"port\":9360}},\"dst\":{\"name\":\"202005080940492786716\",\"partyId\":\"10000\",\"role\":\"fateflow\"},\"command\":{\"name\":\"fateflow\"},\"operator\":\"POST\",\"conf\":{\"overallTimeout\":\"60000\"}}, lastPacketTimestamp: 1588930849341, loopEndTimestamp: 1588930909381\\n\\tat com.webank.ai.fate.networking.proxy.grpc.service.DataTransferPipedServerImpl.unaryCall(DataTransferPipedServerImpl.java:245)\\n\\tat com.webank.ai.fate.api.networking.proxy.DataTransferServiceGrpc$MethodHandlers.invoke(DataTransferServiceGrpc.java:346)\\n\\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)\\n\\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)\\n\\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)\\n\\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\\n\\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\\n\\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\n\\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\n\\tat java.lang.Thread.run(Thread.java:748)\\n\",\"grpc_status\":13}\"\n>"
}

这个error received from peer这两天经常遇到,偶尔会没问题,请教一下,谢谢

**Comment by jiahaoc1993** [comment]
@learningwang 请问下你的部署结构是怎么样的呢？为什么会访问”0.0.0.0:9370“这个地址？

**Comment by learningwang** [comment]
我是用vmware建两台虚拟机,然后严格按照https://github.com/FederatedAI/KubeFATE/blob/master/docker-deploy/README_zh.md进行部署的.
其他什么都没改过.

**Comment by ORANGECAT-S** [comment]
我们遇到的问题有点相似，但是我是在22.17的主机的服务器上使用完全一样的linux版本以及安装步骤，toy执行无误，但在公司其他的主机上部署均会报以下错误；
而且在其他主机上的服务器部署 本地cluster模式的fate，storage-service-cxx服务无法启动,显示
services.sh:行 138;25919 非法指令 （吐核）$module/${target} -p $port -d ${dirdata} > /dev/null
且执行toy时，也会出现以下错误，但在22.17上的服务器使用同样步骤部署本地cluster模式的fate可正常使用。   目前该问题尚未解决，我有点怀疑是机器本身的问题。


报错日志：
(venv) [root@python-6cf9f795c6-s8pkc toy_example]# python run_toy_example.py 9999 9999 1
stdout:{
    "data": {
        "board_url": "http://fateboard:8080/index.html#/dashboard?job_id=202004290851112657102&role=guest&party_id=9999",
        "job_dsl_path": "/data/projects/fate/python/jobs/202004290851112657102/job_dsl.json",
        "job_runtime_conf_path": "/data/projects/fate/python/jobs/202004290851112657102/job_runtime_conf.json",
        "logs_directory": "/data/projects/fate/python/logs/202004290851112657102",
        "model_info": {
            "model_id": "guest-9999#host-9999#model",
            "model_version": "202004290851112657102"
        }
    },
    "jobId": "202004290851112657102",
    "retcode": 0,
    "retmsg": "success"
}


job status is running
"2020-04-29 08:51:13,396 - task_executor.py[line:132] - ERROR: <_Rendezvous of RPC that terminated with:
status = StatusCode.INTERNAL
details = "10.244.4.7:8011: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.webank.ai.eggroll.framework.roll.api.grpc.client.StorageServiceClient.get(StorageServiceClient.java:223)
at com.webank.ai.eggroll.framework.roll.api.grpc.server.RollKvServiceImpl.lambda$get$5(RollKvServiceImpl.java:240)
at com.webank.ai.eggroll.core.api.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:52)
at com.webank.ai.eggroll.framework.roll.api.grpc.server.RollKvServiceImpl.get(RollKvServiceImpl.java:235)
at com.webank.ai.eggroll.api.storage.KVServiceGrpc$MethodHandlers.invoke(KVServiceGrpc.java:959)
at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
at com.webank.ai.eggroll.core.api.grpc.client.GrpcStreamingClientTemplate.calleeStreamingRpcWithImmediateDelayedResult(GrpcStreamingClientTemplate.java:154)
at com.webank.ai.eggroll.framework.roll.api.grpc.client.StorageServiceClient.get(StorageServiceClient.java:219)
... 16 more
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
at io.grpc.Status.asRuntimeException(Status.java:526)
at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
... 5 more
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: egg0/10.103.142.230:7778
at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
... 1 more
Caused by: java.net.ConnectException: Connection refused
... 11 more
"
debug_error_string = "{"created":"@1588150273.394782536","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"10.244.4.7:8011: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException\n\tat com.webank.ai.eggroll.framework.roll.api.grpc.client.StorageServiceClient.get(StorageServiceClient.java:223)\n\tat com.webank.ai.eggroll.framework.roll.api.grpc.server.RollKvServiceImpl.lambda$get$5(RollKvServiceImpl.java:240)\n\tat com.webank.ai.eggroll.core.api.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:52)\n\tat com.webank.ai.eggroll.framework.roll.api.grpc.server.RollKvServiceImpl.get(RollKvServiceImpl.java:235)\n\tat com.webank.ai.eggroll.api.storage.KVServiceGrpc$MethodHandlers.invoke(KVServiceGrpc.java:959)\n\tat io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)\n\tat io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)\n\tat io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)\n\tat io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)\n\tat io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)\n\tat io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)\n\tat io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)\n\tat io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\n\tat io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.reflect.InvocationTargetException\n\tat com.webank.ai.eggroll.core.api.grpc.client.GrpcStreamingClientTemplate.calleeStreamingRpcWithImmediateDelayedResult(GrpcStreamingClientTemplate.java:154)\n\tat com.webank.ai.eggroll.framework.roll.api.grpc.client.StorageServiceClient.get(StorageServiceClient.java:219)\n\t... 16 more\nCaused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception\n\tat io.grpc.Status.asRuntimeException(Status.java:526)\n\tat io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)\n\tat io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)\n\tat io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)\n\tat io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)\n\tat io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)\n\tat io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)\n\tat io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)\n\tat io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)\n\tat io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)\n\tat io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)\n\tat io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)\n\tat io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)\n\tat io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)\n\tat io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)\n\t... 5 more\nCaused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: egg0/10.103.142.230:7778\n\tat sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)\n\tat sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)\n\tat io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)\n\tat io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)\n\tat io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)\n\tat io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)\n\tat io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)\n\tat io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)\n\tat io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)\n\tat io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\t... 1 more\nCaused by: java.net.ConnectException: Connection refused\n\t... 11 more\n","grpc_status":13}"
>"
Traceback (most recent call last):
File "/data/projects/fate/python/fate_flow/driver/task_executor.py", line 119, in run_task
run_object.run(parameters, task_run_args)
File "/data/projects/fate/python/federatedml/toy_example/secure_add_guest.py", line 105, in run
self._init_data()
File "/data/projects/fate/python/federatedml/toy_example/secure_add_guest.py", line 62, in _init_data
self.x = session.parallelize(kvs, include_key=True, partition=self.partition)
File "/data/projects/fate/python/arch/api/utils/profile_util.py", line 31, in _fn
rtn = func(*args, **kwargs)
File "/data/projects/fate/python/arch/api/session.py", line 81, in parallelize
error_if_exist=error_if_exist)
File "/data/projects/fate/python/arch/api/table/eggroll/session_impl.py", line 76, in parallelize
persistent_engine=self._persistent_engine)
File "/data/projects/fate/python/eggroll/api/cluster/eggroll.py", line 410, in parallelize
_table = self._create_table(create_table_info)
File "/data/projects/fate/python/eggroll/api/cluster/eggroll.py", line 443, in _create_table
count = self.eggroll_session._gc_table.get(info.storageLocator.name)
File "/data/projects/fate/python/eggroll/api/cluster/eggroll.py", line 214, in get
return _EggRoll.get_instance().get(self, k, use_serialize=use_serialize)
File "/data/projects/fate/python/eggroll/api/cluster/eggroll.py", line 577, in get
operand = self.kv_stub.get(kv_pb2.Operand(key=k), metadata=_get_meta(_table))
File "/data/projects/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 533, in __call__
return _end_unary_response_blocking(state, call, False, None)
File "/data/projects/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
status = StatusCode.INTERNAL
details = "10.244.4.7:8011: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.webank.ai.eggroll.framework.roll.api.grpc.client.StorageServiceClient.get(StorageServiceClient.java:223)
at com.webank.ai.eggroll.framework.roll.api.grpc.server.RollKvServiceImpl.lambda$get$5(RollKvServiceImpl.java:240)
at com.webank.ai.eggroll.core.api.grpc.server.GrpcServerWrapper.wrapGrpcServerRunnable(GrpcServerWrapper.java:52)
at com.webank.ai.eggroll.framework.roll.api.grpc.server.RollKvServiceImpl.get(RollKvServiceImpl.java:235)
at com.webank.ai.eggroll.api.storage.KVServiceGrpc$MethodHandlers.invoke(KVServiceGrpc.java:959)
at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
at com.webank.ai.eggroll.core.api.grpc.client.GrpcStreamingClientTemplate.calleeStreamingRpcWithImmediateDelayedResult(GrpcStreamingClientTemplate.java:154)
at com.webank.ai.eggroll.framework.roll.api.grpc.client.StorageServiceClient.get(StorageServiceClient.java:219)
... 16 more
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
at io.grpc.Status.asRuntimeException(Status.java:526)
at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
... 5 more
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: egg0/10.103.142.230:7778
at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

**Comment by learningwang** [comment]
0.0.0.0:9370是我的faderatedai/proxy docker的地址
[root@localhost ~]# docker ps
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS                                                      NAMES
1af293587405        federatedai/serving-server:1.2.2-release   "/bin/sh -c 'java -c…"   16 hours ago        Up 16 hours         0.0.0.0:8000->8000/tcp                                     serving-9999_serving-server_1
e591c1b944a0        redis:5                                    "docker-entrypoint.s…"   16 hours ago        Up 16 hours         6379/tcp                                                   serving-9999_redis_1
f88b079587fb        federatedai/serving-proxy:1.2.2-release    "/bin/sh -c 'java -D…"   16 hours ago        Up 16 hours         0.0.0.0:8059->8059/tcp, 0.0.0.0:8869->8869/tcp, 8879/tcp   serving-9999_serving-proxy_1
ab4ff65bcf28        federatedai/fateboard:1.3.0-release        "/bin/sh -c 'java -D…"   16 hours ago        Up 16 hours         0.0.0.0:8080->8080/tcp                                     confs-9999_fateboard_1
e33713925675        federatedai/python:1.3.0-release           "/bin/sh -c 'sleep 5…"   16 hours ago        Up 16 hours         0.0.0.0:9360->9360/tcp, 0.0.0.0:9380->9380/tcp             confs-9999_python_1
39adc23db1ca        federatedai/roll:1.3.0-release             "/bin/sh -c 'java -c…"   16 hours ago        Up 16 hours         8011/tcp                                                   confs-9999_roll_1
54b913356012        federatedai/meta-service:1.3.0-release     "/bin/sh -c 'java -c…"   16 hours ago        Up 16 hours         8590/tcp                                                   confs-9999_meta-service_1
b79013e69a3b        federatedai/egg:1.3.0-release              "/bin/sh -c 'cd /dat…"   16 hours ago        Up 16 hours         7778/tcp, 7888/tcp, 50000-60000/tcp                        confs-9999_egg_1
d4e28e864cd8        mysql:8                                    "docker-entrypoint.s…"   16 hours ago        Up 16 hours         3306/tcp, 33060/tcp                                        confs-9999_mysql_1
41fbf13bd2b4        redis:5                                    "docker-entrypoint.s…"   16 hours ago        Up 16 hours         6379/tcp                                                   confs-9999_redis_1
4487283ded48        federatedai/federation:1.3.0-release       "/bin/sh -c 'java -c…"   16 hours ago        Up 16 hours         9394/tcp                                                   confs-9999_federation_1
bccb80c33aeb        federatedai/proxy:1.3.0-release            "/bin/sh -c 'java -c…"   16 hours ago        Up 16 hours         0.0.0.0:9370->9370/tcp                                     confs-9999_proxy_1
[root@localhost ~]#

**Comment by jiahaoc1993** [comment]
@ORANGECAT-S 我们wiki有提及到指令集的问题，可以确认下。

**Comment by jiahaoc1993** [comment]
@learningwang 我觉得可能你把parties.conf写错了，能否贴出来看看？

**Comment by learningwang** [comment]
> @learningwang 我觉得可能你把parties.conf写错了，能否贴出来看看？
136和137对应我的两台虚拟机,这个paries.conf是136上的文件

#!/bin/bash

user=root
dir=/data/projects/fate
partylist=(10000 9999)
partyiplist=(192.168.216.136 192.168.216.137)
servingiplist=(192.168.216.136 192.168.216.137)

# party 1 will host the exchange by default
exchangeip=

**Comment by ORANGECAT-S** [comment]
我是使用k8s和本地集群模式部署的fate，和这个配置没有关系，而且我确定我的安装步骤以及相关配置无误。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "learningwang"<notifications@github.com&gt;; 
发送时间: 2020年5月14日(星期四) 中午11:24
收件人: "FederatedAI/KubeFATE"<KubeFATE@noreply.github.com&gt;; 
抄送: "Q宋先生"<342695614@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [FederatedAI/KubeFATE] 提交任务时报错,&quot;description&quot;:&quot;Error received from peer&quot; (#129)





  
@learningwang 我觉得可能你把parties.conf写错了，能否贴出来看看？
 136和137对应我的两台虚拟机,这个paries.conf是136上的文件
  
#!/bin/bash
 
user=root
 dir=/data/projects/fate
 partylist=(10000 9999)
 partyiplist=(192.168.216.136 192.168.216.137)
 servingiplist=(192.168.216.136 192.168.216.137)
 
party 1 will host the exchange by default
 
exchangeip=

**Comment by xby8888** [comment]
请问楼主问题解决了吗，遇到同样的问题

**Comment by rishy** [comment]
> 我们wiki有提及到指令集的问题，可以确认下。

What wiki? Can you please share the link?

**Comment by yumiaoGitHub** [comment]
遇到同样的问题，如果问题解决了感谢及时更新一下

**Comment by owlet42** [comment]
Please view this page, https://github.com/FederatedAI/KubeFATE/wiki/KubeFATE-FAQs#usage

**Comment by LaynePeng** [comment]
Close this issue because no follow-up response.
