### ISSUE TITLE
docker版本部署后运行测试样例出错

### ISSUE THREAD

**Issue by KAndHisC** [FederatedAI/KubeFATE#20]
一开始的时候我使用非docker方式部署了两个FATE，运行正常，后来出现docker版本后，将其中一方切换到docker版本，发现通信失败，不知道是否两个版本不能兼容运行。
为解决这种情况，我尝试将两个party都部署了docker版本，在两边都运行测试样例，结果如下：
------
两个party 分别为10000和10004
------
在10000上运行python run_toy_example.py 10000 10004 1
```
(venv) [root@d94a571e5e8f toy_example]# python run_toy_example.py 10000 10004 1
stdout:{
    "data": {
        "board_url": "http://fateboard:8080/index.html#/dashboard?job_id=2019103103130742954512&role=guest&party_id=10000",
        "job_dsl_path": "/data/projects/fate/python/jobs/2019103103130742954512/job_dsl.json",
        "job_runtime_conf_path": "/data/projects/fate/python/jobs/2019103103130742954512/job_runtime_conf.json",
        "model_info": {
            "model_id": "guest-10000#host-10004#model",
            "model_version": "2019103103130742954512"
        }
    },
    "jobId": "2019103103130742954512",
    "meta": null,
    "retcode": 0,
    "retmsg": "success"
}


toy example is running, jobid is 2019103103130742954512
job status is running
"2019-10-31 03:13:08,784 - task_executor.py[line:123] - ERROR: <_Rendezvous of RPC that terminated with:
status = StatusCode.UNAVAILABLE
details = "Name resolution failure"
debug_error_string = "{"created":"@1572491588.784572961","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2721,"referenced_errors":[{"created":"@1572491588.784570308","description":"Name resolution failure","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3026,"grpc_status":14}]}"
>"
Traceback (most recent call last):
File "/data/projects/fate/python/fate_flow/driver/task_executor.py", line 112, in run_task
run_object.run(parameters, task_run_args)
File "/data/projects/fate/python/federatedml/toy_example/secure_add_guest.py", line 106, in run
self.sync_share_to_host()
File "/data/projects/fate/python/federatedml/toy_example/secure_add_guest.py", line 81, in sync_share_to_host
idx=0)
File "/data/projects/fate/python/arch/api/federation.py", line 73, in remote
return RuntimeInstance.FEDERATION.remote(obj=obj, name=name, tag=tag, role=role, idx=idx)
File "/data/projects/fate/python/arch/api/cluster/federation.py", line 182, in remote
type=federation_pb2.SEND))
File "/data/projects/fate/venv/lib/python3.6/site-packages/grpc/_channel.py", line 533, in __call__
return _end_unary_response_blocking(state, call, False, None)
File "/data/projects/fate/venv/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
status = StatusCode.UNAVAILABLE
details = "Name resolution failure"
debug_error_string = "{"created":"@1572491588.784572961","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2721,"referenced_errors":[{"created":"@1572491588.784570308","description":"Name resolution failure","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3026,"grpc_status":14}]}"
>
```
在10004上运行python run_toy_example.py 10004 10000 1
```
(venv) [root@e64635054c61 toy_example]# python run_toy_example.py 10004 10000 1
stdout:{
    "data": {
        "board_url": "http://fateboard:8080/index.html#/dashboard?job_id=201910310311108975682&role=guest&party_id=10004",
        "job_dsl_path": "/data/projects/fate/python/jobs/201910310311108975682/job_dsl.json",
        "job_runtime_conf_path": "/data/projects/fate/python/jobs/201910310311108975682/job_runtime_conf.json",
        "model_info": {
            "model_id": "guest-10004#host-10000#model",
            "model_version": "201910310311108975682"
        }
    },
    "jobId": "201910310311108975682",
    "meta": null,
    "retcode": 0,
    "retmsg": "success"
}


toy example is running, jobid is 201910310311108975682
job status is running
Traceback (most recent call last):
  File "run_toy_example.py", line 197, in <module>
    exec_toy_example(runtime_config)
  File "run_toy_example.py", line 171, in exec_toy_example
    show_log(jobid, "error")
  File "run_toy_example.py", line 149, in show_log
    with open(error_log, "r") as fin:
FileNotFoundError: [Errno 2] No such file or directory: '/data/projects/fate/python/examples/toy_example/test/log/job_201910310311108975682_log/guest/10004/secure_add_example_0/ERROR.log'
```
两者都成功启动了任务，但是从报错结果的不对称来看，我猜测其中有一方出错了，但是不知道报错的原因。双方部署的流程配置并无不同。

**Comment by KAndHisC** [comment]
我检查了docker ps，
federatedai/federation:1.0.2-release       "/bin/sh -c 'cd /dat…"   About an hour ago   Up 25 minutes       9394/tcp                              confs-10004_federation_1
这个容器一直没有启动，我重复启动几次都失败了。
重新运行sh docker-auto-deploy.sh解决了这个问题。如果有人明白之前发生了什么错误，可以继续评论，谢谢！

**Comment by yuyan110nan** [comment]
我部署1.3的时候出现了同样的问题，但是confs-10000_federation_1容器正常启动，部署单一服务器运行toyexample没有问题，但是部署两方服务器运行失败，报错如下，您现在知道是什么原因了吗？
stdout:{
    "retcode": 100,
    "retmsg": "rpc request error: <_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"io exception\"\n\tdebug_error_string = \"{\"created\":\"@1591020347.435712485\",\"description\":\"Error received from peer\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1017,\"grpc_message\":\"io exception\",\"grpc_status\":14}\"\n>"
}


Traceback (most recent call last):
  File "run_toy_example.py", line 197, in <module>
    exec_toy_example(runtime_config)
  File "run_toy_example.py", line 161, in exec_toy_example
    jobid = exec_task(dsl_path, runtime_config)
  File "run_toy_example.py", line 91, in exec_task
    "failed to exec task, status:{}, stderr is {} stdout:{}".format(status, stderr, stdout))
ValueError: failed to exec task, status:100, stderr is None stdout:{'retcode': 100, 'retmsg': 'rpc request error: <_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "io exception"\n\tdebug_error_string = "{"created":"@1591020347.435712485","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"io exception","grpc_status":14}"\n>'}

**Comment by zhouyoupku** [comment]
遇到了同样的问题。请问问题解决了吗？ @yuyan110nan

**Comment by yuyan110nan** [comment]
我是用阿里云服务器搭建的两台服务器，云服务器之前如果是不同地域的话默认通讯端口不通，需要开通高速通道（收费）创建安全组后才能开放端口

**Comment by 1treeup** [comment]
相同地域的话要开放哪些端口才能正常运行啊。
