### ISSUE TITLE
confs-10000_python_1一直重启，peewee.InterfaceError: Error, database must be initialized before opening a connection.

### ISSUE THREAD

**Issue by shizihao765** [FederatedAI/KubeFATE#254]
**What deployment mode you are use?  **
1. docker-compose;

**What KubeFATE and FATE version you are using?  **
1.4.4
**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: centos7
 - Version 7.8

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome

**To Reproduce**
按照README部署

**What happen?**
容器confs-10000_python_1一直在重启。log显示peewee.InterfaceError: Error, database must be initialized before opening a connection.

**Screenshots**
```bash
[root@localhost confs-10000]# docker ps
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS                          PORTS                                                      NAMES
40667c98a741        federatedai/serving-proxy:2.0.0-release   "/bin/sh -c 'java -D…"   8 minutes ago       Up 8 minutes                    0.0.0.0:8059->8059/tcp, 0.0.0.0:8869->8869/tcp, 8879/tcp   serving-10000_serving-proxy_1
fb7175084c53        federatedai/fateboard:1.4.4-release       "/bin/sh -c 'java -D…"   9 minutes ago       Up 9 minutes                    0.0.0.0:8080->8080/tcp                                     confs-10000_fateboard_1
fb0e2d5bbeaf        federatedai/client:1.4.4-release          "/bin/sh -c 'jupyter…"   9 minutes ago       Up 9 minutes                    0.0.0.0:20000->20000/tcp                                   confs-10000_client_1
56a7d0cad004        federatedai/python:1.4.4-release          "/bin/sh -c 'sleep 5…"   9 minutes ago       Restarting (1) 29 seconds ago                                                              confs-10000_python_1
b296a36e7f2b        federatedai/eggroll:1.4.4-release         "bash -c 'java -Dlog…"   9 minutes ago       Up 9 minutes                    4670/tcp                                                   confs-10000_clustermanager_1
cfabf0627e11        federatedai/eggroll:1.4.4-release         "bash -c 'java -Dlog…"   9 minutes ago       Up 9 minutes                    4671/tcp                                                   confs-10000_nodemanager_1
6ae9e2a97858        federatedai/eggroll:1.4.4-release         "bash -c 'java -Dlog…"   9 minutes ago       Up 9 minutes                    0.0.0.0:9370->9370/tcp                                     confs-10000_rollsite_1
eeeb6aec47db        mysql:8                                   "docker-entrypoint.s…"   9 minutes ago       Up 9 minutes                    3306/tcp, 33060/tcp                                        confs-10000_mysql_1

```

```bash
[root@localhost confs-10000]# docker logs            56a7d0cad004
Traceback (most recent call last):
  File "./fate_flow/fate_flow_server.py", line 87, in <module>
    init_database_tables()
  File "/data/projects/fate/python/fate_flow/db/db_models.py", line 103, in init_database_tables
    with DB.connection_context():
  File "/data/projects/python/venv/lib/python3.6/site-packages/peewee.py", line 2724, in __enter__
    self.db.connect()
  File "/data/projects/python/venv/lib/python3.6/site-packages/playhouse/pool.py", line 108, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
  File "/data/projects/python/venv/lib/python3.6/site-packages/peewee.py", line 2808, in connect
    raise InterfaceError('Error, database must be initialized '
peewee.InterfaceError: Error, database must be initialized before opening a connection.
```

**Additional context**

**Comment by FeynmanDNA** [comment]
same issue here. I think it is probably due to 1.4.4 release.

i tried with 1.3.0 and 1.3.0-a docker-compose release, the python container restart issue went away

**Comment by jiahaoc1993** [comment]
@shizihao765 it is normal that the python container restarts several times, you can also check the log from the mysql see if the initialization is success.
