### ISSUE TITLE
Pod got stuck in CrashLoopBackOff due to FileNotFoundException

### ISSUE THREAD

**Issue by Chenfengldw** [FederatedAI/KubeFATE#32]
After helm install fate-10000, fate-9999, fate-exchange, and run
 `kubectl -n fate-10000 get pod`
 found that many pod got stuck in CrashLoopBackOff;
for example egg-756d95b5b8-dhrjr pod using  federatedai/egg:1.1-release image. 
Run
`kubectl logs -n fate-10000 egg-756d95b5b8-dhrjr`
got:

> Exception in thread "main" org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from class path resource [applicationContext-egg.xml]; nested exception is java.io.FileNotFoundException: class path resource [applicationContext-egg.xml] cannot be opened because it does not exist
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:344)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:224)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:195)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:257)
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:128)
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:94)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:133)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:636)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:521)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:85)
	at com.webank.ai.eggroll.framework.egg.Egg.main(Egg.java:47)
Caused by: java.io.FileNotFoundException: class path resource [applicationContext-egg.xml] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:330)
	... 13 more

**Comment by owlet42** [comment]
You can try it with the latest code
updated the k8s deployment for fate1.1 #30

**Comment by Chenfengldw** [comment]
Successfully deployed with the latest code
