### ISSUE TITLE
Fate Flow server keeps restarting due python import module not in requirements

### ISSUE THREAD

**Issue by victorperezc** [FederatedAI/KubeFATE#333]
**What deployment mode you are use?  **
1. docker-compose;

**What KubeFATE and FATE version you are using?  **
1.5.0

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: Ubuntu 
 - Version : 20.4

**To Reproduce**
Follow https://blog.csdn.net/liudongdong19/article/details/105464444

**What happen?**
fate_flow server can't import futures from concurrent (module), therefore the container would never run

**Screenshots**
<img width="1680" alt="Screenshot 2021-01-19 at 14 07 38" src="https://user-images.githubusercontent.com/40391895/105045319-b2050b00-5a5f-11eb-82a4-bf40783cba53.png">

**Comment by Victorpc98** [comment]
Seems like the futures module comes natively with python 3 but not python 2. Anyone knows how to fix this?

**Comment by tanyatanyatanya** [comment]
I met it, too

**Comment by tanyatanyatanya** [comment]
You can try using ‘wget https://github.com/FederatedAI/KubeFATE/releases/download/v1.5.0/kubefate-docker-compose-v1.5.0.tar.gz’ to download the docker-compose installation package

**Comment by owlet42** [comment]
Please delete and deploy again。
How to delete(https://github.com/FederatedAI/KubeFATE/tree/master/docker-deploy#deleting-cluster)

**Comment by cqycsxf** [comment]
> You can try using ‘wget [https://github.com/FederatedAI/KubeFATE/releases/download/v1.5.0/kubefate-docker-compose-v1.5.0.tar.gz’](https://github.com/FederatedAI/KubeFATE/releases/download/v1.5.0/kubefate-docker-compose-v1.5.0.tar.gz%E2%80%99) to download the docker-compose installation package

I use docker-compose installation package to deploy, met the same issue

**Comment by cqycsxf** [comment]
> You can try using ‘wget [https://github.com/FederatedAI/KubeFATE/releases/download/v1.5.0/kubefate-docker-compose-v1.5.0.tar.gz’](https://github.com/FederatedAI/KubeFATE/releases/download/v1.5.0/kubefate-docker-compose-v1.5.0.tar.gz%E2%80%99) to download the docker-compose installation package

I use kubefate-docker-compose-v1.5.0.tar.gz deploy, the confs(id)_python_1 container seems can not link the mysql, logs as follow
Traceback (most recent call last):
  File "/data/projects/python/venv/lib/python3.6/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/data/projects/python/miniconda3/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/data/projects/python/miniconda3/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/projects/python/venv/lib/python3.6/site-packages/peewee.py", line 2817, in connect
    self._state.set_connection(self._connect())
  File "/data/projects/python/venv/lib/python3.6/site-packages/playhouse/pool.py", line 155, in _connect
    conn = super(PooledDatabase, self)._connect()
  File "/data/projects/python/venv/lib/python3.6/site-packages/peewee.py", line 3642, in _connect
    conn = mysql.connect(db=self.database, **self.connect_params)
  File "/data/projects/python/venv/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/data/projects/python/venv/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/data/projects/python/venv/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'mysql' ([Errno 111] Connection refused)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./fate_flow/fate_flow_server.py", line 91, in <module>
    init_flow_db()
  File "/data/projects/python/venv/lib/python3.6/site-packages/peewee.py", line 393, in inner
    with self:
  File "/data/projects/python/venv/lib/python3.6/site-packages/peewee.py", line 2724, in __enter__
    self.db.connect()
  File "/data/projects/python/venv/lib/python3.6/site-packages/playhouse/pool.py", line 108, in connect
    return super(PooledDatabase, self).connect(reuse_if_open)
  File "/data/projects/python/venv/lib/python3.6/site-packages/peewee.py", line 2820, in connect
    self._initialize_connection(self._state.conn)
  File "/data/projects/python/venv/lib/python3.6/site-packages/peewee.py", line 2666, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/data/projects/python/venv/lib/python3.6/site-packages/peewee.py", line 179, in reraise
    raise value.with_traceback(tb)
  File "/data/projects/python/venv/lib/python3.6/site-packages/peewee.py", line 2817, in connect
    self._state.set_connection(self._connect())
  File "/data/projects/python/venv/lib/python3.6/site-packages/playhouse/pool.py", line 155, in _connect
    conn = super(PooledDatabase, self)._connect()
  File "/data/projects/python/venv/lib/python3.6/site-packages/peewee.py", line 3642, in _connect
    conn = mysql.connect(db=self.database, **self.connect_params)
  File "/data/projects/python/venv/lib/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/data/projects/python/venv/lib/python3.6/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/data/projects/python/venv/lib/python3.6/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
peewee.OperationalError: (2003, "Can't connect to MySQL server on 'mysql' ([Errno 111] Connection refused)")
 * Running on http://192.167.0.100:9380/ (Press CTRL+C to quit)

**Comment by LaynePeng** [comment]
Close this issue because it is an old version problem.
