### ISSUE TITLE
hetero_secureboost fail becase No module named 'torch' how can i fix this

### ISSUE THREAD

**Issue by JanYunkai** [FederatedAI/KubeFATE#365]
**What deployment mode you are use?  **
2. Kuberentes.

**What KubeFATE and FATE version you are using?  **
KubeFATE 
**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **

**Desktop (please complete the following information):**

**To Reproduce**
Clear how to reproduce your problem.

**What happen?**

ModuleNotFoundError: No module named 'torch'

**Screenshots**

`
[ERROR] [2021-03-02 10:41:40,991] [5448:140428980160320] - task_executor.py[line:196]: No module named 'torch'
2
Traceback (most recent call last):
3
  File "./fate/python/fate_flow/operation/task_executor.py", line 169, in run_task
4
    run_object = getattr(importlib.import_module(run_class_package), run_class_name)()
5
  File "/opt/app-root/lib64/python3.6/importlib/__init__.py", line 126, in import_module
5
  File "/opt/app-root/lib64/python3.6/importlib/__init__.py", line 126, in import_module
6
    return _bootstrap._gcd_import(name[level:], package, level)
7
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
8
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
9
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
10
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
11
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
12
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
13
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
14
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
15
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
16
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
17
  File "./fate/python/federatedml/statistic/intersect/__init__.py", line 17, in <module>
18
    from federatedml.statistic.intersect.intersect import Intersect
19
  File "./fate/python/federatedml/statistic/intersect/intersect.py", line 18, in <module>
20
    from federatedml.secureprotol.encode import Encode
21
  File "./fate/python/federatedml/secureprotol/__init__.py", line 17, in <module>
22
    from federatedml.secureprotol.encrypt import RsaEncrypt, PaillierEncrypt, FakeEncrypt, AffineEncrypt, IterativeAffineEncrypt
23
  File "./fate/python/federatedml/secureprotol/encrypt.py", line 21, in <module>
24
    import torch
25
ModuleNotFoundError: No module named 'torch'
26
[ERROR] [2021-03-02 10:41:52,709] [5525:140356482094912] - task_executor.py[line:196]: No module named 'torch'
27
Traceback (most recent call last):
28
  File "./fate/python/fate_flow/operation/task_executor.py", line 169, in run_task
29
    run_object = getattr(importlib.import_module(run_class_package), run_class_name)()
30
  File "/opt/app-root/lib64/python3.6/importlib/__init__.py", line 126, in import_module
31
    return _bootstrap._gcd_import(name[level:], package, level)
32
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
33
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
34
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
35
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
36
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
`

**Additional context**

https://github.com/FederatedAI/FATE/tree/master/examples/dsl/v2/hetero_secureboost

test this example

**Comment by JanYunkai** [comment]
我通过kubectl exec 进入 pod/python 内部执行了pip install .我想知道从框架层面怎么保证pod每次都安装指定的包

**Comment by jiahaoc1993** [comment]
@JanYunkai hi, we already update the python image with torch package. Please re-download the latest federatedai images.

**Comment by JanYunkai** [comment]
> @JanYunkai hi, we already update the python image with torch package. Please re-download the latest federatedai images.

thx

**Comment by JanYunkai** [comment]
> @JanYunkai hi, we already update the python image with torch package. Please re-download the latest federatedai images.

hub.c.163.com please
