### ISSUE TITLE
toy issue cannot run

### ISSUE THREAD

**Issue by cometta** [FederatedAI/KubeFATE#40]
I am testing the docker example. After executed python run_toy_example.py 10000 9999 1  ,
fate_flow_client.py, `response = requests.post("/".join([server_url, "job", func.rstrip('_job')]), json=post_data)` , return error `{'retcode': 100, 'retmsg': 'rpc request error: <_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "io exception"\n\tdebug_error_string = "{"created":"@1574410850.912361635","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"io exception","grpc_status":14}"\n>'}
{
    "retcode": 100,
    "retmsg": "rpc request error: <_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"io exception\"\n\tdebug_error_string = \"{\"created\":\"@1574410850.912361635\",\"description\":\"Error received from peer\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1017,\"grpc_message\":\"io exception\",\"grpc_status\":14}\"\n>"
}`

log from federatedai/python:1.1-release, show
```
[2019-11-22 08:20:50,912] ERROR in app: Exception on /submit [POST]
Traceback (most recent call last):
  File "/data/projects/fate/python/fate_flow/utils/api_utils.py", line 66, in remote_api
    #stat_logger.info("grpc api request: {}".format(_packet))
  File "/data/projects/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 533, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/data/projects/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "io exception"
	debug_error_string = "{"created":"@1574410850.912361635","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"io exception","grpc_status":14}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/projects/python/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/projects/python/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/projects/python/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/projects/python/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/data/projects/python/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/projects/python/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/projects/fate/python/fate_flow/apps/job_app.py", line 45, in submit_job
    job_id, job_dsl_path, job_runtime_conf_path, logs_directory, model_info, board_url = JobController.submit_job(request.json)
  File "/data/projects/fate/python/fate_flow/driver/job_controller.py", line 92, in submit_job
    TaskScheduler.distribute_job(job=job, roles=job_runtime_conf['role'], job_initiator=job_initiator)
  File "/data/projects/fate/python/fate_flow/driver/task_scheduler.py", line 55, in distribute_job
    work_mode=job.f_work_mode)
  File "/data/projects/fate/python/fate_flow/utils/api_utils.py", line 53, in federated_api
    dest_party_id=dest_party_id, json_body=json_body, overall_timeout=overall_timeout)
  File "/data/projects/fate/python/fate_flow/utils/api_utils.py", line 72, in remote_api
    except grpc.RpcError as e:
Exception: rpc request error: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "io exception"
	debug_error_string = "{"created":"@1574410850.912361635","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"io exception","grpc_status":14}"
>
```

**Comment by jiahaoc1993** [comment]
@cometta please check if all containers are running properly. If yes, please details your process to run the toy example.

**Comment by LaynePeng** [comment]
@cometta have you solved the problem?

**Comment by jiahaoc1993** [comment]
Since the issue's owner is not activated, let's close it now.
