### ISSUE TITLE
start up docker confs-9999_python_1 and confs-10000_python_1 have error

### ISSUE THREAD

**Issue by cometta** [FederatedAI/KubeFATE#41]
when i start the docker containers, i see below errors in confs-10000_python_1, confs-9999_python_1

```
Traceback (most recent call last):
  File "fate_flow_server.py", line 91, in <module>
    session.init(mode=RuntimeConfig.WORK_MODE, backend=Backend.EGGROLL)
  File "/data/projects/fate/python/arch/api/session.py", line 50, in init
    session = build_session(job_id=job_id, work_mode=mode, backend=backend)
  File "/data/projects/fate/python/arch/api/table/session.py", line 34, in build_session
    session = session_impl.FateSessionImpl(eggroll_session, work_mode)
  File "/data/projects/fate/python/arch/api/table/eggroll/session_impl.py", line 32, in __init__
    self._eggroll = eggroll_util.build_eggroll_runtime(work_mode=work_mode, eggroll_session=eggroll_session)
  File "/data/projects/fate/python/arch/api/table/eggroll_util.py", line 44, in build_eggroll_runtime
    return eggroll_init(eggroll_session)
  File "/data/projects/fate/python/eggroll/api/cluster/eggroll.py", line 79, in eggroll_init
    eggroll_runtime = _EggRoll(eggroll_session=eggroll_session)
  File "/data/projects/fate/python/eggroll/api/cluster/eggroll.py", line 364, in __init__
    self.session_stub.getOrCreateSession(self.eggroll_session.to_protobuf())
  File "/data/projects/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 533, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/data/projects/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connect Failed"
	debug_error_string = "{"created":"@1574473852.541712846","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2721,"referenced_errors":[{"created":"@1574473852.541710746","description":"Pick Cancelled","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":241,"referenced_errors":[{"created":"@1574473852.541691945","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":689,"grpc_status":14,"referenced_errors":[{"created":"@1574473852.541670345","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":205,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:172.19.0.8:8011"}]}]}]}"
>
created table: storage_type: LMDB, namespace: b3844b54-0d93-11ea-8b9f-0242ac130009, name: __gc_b3844b54-0d93-11ea-8b9f-0242ac130009, partitions: 1, in_place_computing: False
 * Running on http://0.0.0.0:9380/ (Press CTRL+C to quit)
```

roll container does not have error
```
[INFO ] 2019-11-23T01:50:52,103 [main] [ThreadPoolTaskExecutor:171] - Initializing ExecutorService
[INFO ] 2019-11-23T01:50:52,154 [main] [PostProcessorRegistrationDelegate$BeanPostProcessorChecker:330] - Bean 'asyncThreadPool' of type [org.springframework.scheduling.config.TaskExecutorFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO ] 2019-11-23T01:50:52,160 [main] [PostProcessorRegistrationDelegate$BeanPostProcessorChecker:330] - Bean 'asyncThreadPool' of type [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO ] 2019-11-23T01:50:54,326 [main] [ThreadPoolTaskExecutor:171] - Initializing ExecutorService
[INFO ] 2019-11-23T01:50:54,346 [main] [ThreadPoolTaskExecutor:171] - Initializing ExecutorService
[INFO ] 2019-11-23T01:50:54,471 [main] [ThreadPoolTaskScheduler:171] - Initializing ExecutorService 'routineScheduler'
[INFO ] 2019-11-23T01:50:54,695 [main] [DefaultGrpcServerFactory:119] - final conf path: /data/projects/fate/roll/conf/roll.properties
[INFO ] 2019-11-23T01:50:55,130 [pool-3-thread-1] [GrpcChannelFactory:108] - [COMMON][CHANNEL][CREATE] creating insecure channel for endpoint: ip: meta-service, port: 8590, hostname:
[INFO ] 2019-11-23T01:50:55,429 [pool-3-thread-1] [GrpcChannelFactory:201] - [COMMON][CHANNEL][CREATE] creating channel to {"ip":"meta-service","port":8590,"hostname":""}, isSecure: false
[INFO ] 2019-11-23T01:50:55,818 [pool-3-thread-1] [GrpcChannelFactory:231] - [COMMON][CHANNEL][CREATE] created channel to {"ip":"meta-service","port":8590,"hostname":""}, isSecure: false
[INFO ] 2019-11-23T01:50:56,013 [main] [DefaultGrpcServerFactory:62] - server build on port only :8011
[INFO ] 2019-11-23T01:51:01,416 [grpcServiceExecutor-1] [RollSessionServiceImpl:33] - [ROLL][SESSION] getOrCreateSession. request: {"sessionId":"b3844b54-0d93-11ea-8b9f-0242ac130009","computingEngineConf":{"eggroll.roll.port":"8011","eggroll.server.conf.path":"eggroll/conf/server_conf.json","eggroll.roll.host":"roll"},"namingPolicy":"DEFAULT","tag":""}
[INFO ] 2019-11-23T01:51:01,465 [grpcServiceExecutor-1] [RollKvServiceImpl:119] - Kv.createIfAbsent request received. request: {"storageLocator":{"type":"LMDB","namespace":"b3844b54-0d93-11ea-8b9f-0242ac130009","name":"__gc_b3844b54-0d93-11ea-8b9f-0242ac130009","fragment":0},"fragmentCount":1}
```

**Comment by jiahaoc1993** [comment]
@cometta hi, can you paste the full log of the egg and roll container?
