### ISSUE TITLE
run demo error

### ISSUE THREAD

**Issue by tangyuxiaoyao** [FederatedAI/KubeFATE#45]
demo: python run_toy_example.py 10000 10000 1
error as below:
"2019-11-25 04:01:52,599 - task_executor.py[line:127] - ERROR: must be real number, not NoneType"
Traceback (most recent call last):
File "/data/projects/fate/python/fate_flow/driver/task_executor.py", line 118, in run_task
run_object.run(parameters, task_run_args)
File "/data/projects/fate/python/federatedml/toy_example/secure_add_guest.py", line 130, in run
secure_sum = self.reconstruct(guest_sum, host_sum)
File "/data/projects/fate/python/federatedml/toy_example/secure_add_guest.py", line 71, in reconstruct
print("host sum is %.4f" % host_sum)
TypeError: must be real number, not NoneType

anthor error:
Nov 25, 2019 7:30:20 AM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=95, target=federation:9394} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:103)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:411)
	at com.webank.ai.fate.networking.proxy.factory.GrpcStubFactory.createChannel(GrpcStubFactory.java:221)
	at com.webank.ai.fate.networking.proxy.factory.GrpcStubFactory.access$100(GrpcStubFactory.java:51)
	at com.webank.ai.fate.networking.proxy.factory.GrpcStubFactory$1.load(GrpcStubFactory.java:89)
	at com.webank.ai.fate.networking.proxy.factory.GrpcStubFactory$1.load(GrpcStubFactory.java:83)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.webank.ai.fate.networking.proxy.factory.GrpcStubFactory.getChannel(GrpcStubFactory.java:157)
	at com.webank.ai.fate.networking.proxy.factory.GrpcStubFactory.getStubBase(GrpcStubFactory.java:123)
	at com.webank.ai.fate.networking.proxy.factory.GrpcStubFactory.getAsyncStub(GrpcStubFactory.java:113)
	at com.webank.ai.fate.networking.proxy.factory.GrpcStubFactory.getAsyncStub(GrpcStubFactory.java:109)
	at com.webank.ai.fate.networking.proxy.grpc.client.DataTransferPipedClient.getStub(DataTransferPipedClient.java:215)
	at com.webank.ai.fate.networking.proxy.grpc.client.DataTransferPipedClient.unaryCall(DataTransferPipedClient.java:183)
	at com.webank.ai.fate.networking.proxy.service.CascadedCaller.run(CascadedCaller.java:64)
	at com.webank.ai.fate.networking.proxy.service.CascadedCaller$$FastClassBySpringCGLIB$$5248343b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[confs-10000.zip](https://github.com/FederatedAI/KubeFATE/files/3885333/confs-10000.zip)

**Comment by jiahaoc1993** [comment]
@tangyuxiaoyao Could paste the configuration files of the party 10000 here too?

**Comment by tangyuxiaoyao** [comment]
@jiahaoc1993 
[confs-10000_config.zip](https://github.com/FederatedAI/KubeFATE/files/3885385/confs-10000_config.zip)

**Comment by jiahaoc1993** [comment]
@tangyuxiaoyao please check if the prox is working properly.
