### ISSUE TITLE
1.6.1版本docker部署spark-rabbitmq，run_toy_example时报错json解析失败了

### ISSUE THREAD

**Issue by jojotaro123** [FederatedAI/KubeFATE#487]
报错堆栈如下，dockre容器全部正常启动
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/projects/fate/python/fate_flow/apps/job_app.py", line 50, in submit_job
    submit_result = DAGScheduler.submit(request.json)
  File "/data/projects/fate/python/fate_flow/scheduler/dag_scheduler.py", line 119, in submit
    raise Exception("create job failed", response)
Exception: ('create job failed', {'host': {9999: {'retcode': <RetCode.FEDERATED_ERROR: 104>, 'retmsg': 'Federated schedule error, remote http request error: Expecting value: line 1 column 1 (char 0)'}}, 'guest': {10000: {'retcode': <RetCode.FEDERATED_ERROR: 104>, 'retmsg': 'Federated schedule error, remote http request error: Expecting value: line 1 column 1 (char 0)'}}})

**Comment by jojotaro123** [comment]
![image](https://user-images.githubusercontent.com/62503095/140286669-50a972bb-10c8-4e84-b5c5-877ffbf33a97.png)
求助啊

**Comment by owlet42** [comment]
Please confirm that the release version you are using is https://github.com/FederatedAI/KubeFATE/releases/tag/v1.6.1 , including the version of the image.
The test can run successfully on OS CentOS7 and Docker v20.10.7.

**Comment by JingChen23** [comment]
This version is nologiner support, please try v1.8.0.
