### ISSUE TITLE
Can't run with Neural Networks

### ISSUE THREAD

**Issue by katerina-merkulova** [FederatedAI/KubeFATE#489]
I tried to run FATE in federated manner with docker-compose. So, examples for all models work but hetero-nn and homo-nn both on Keras and PyTorch. 

1. With Keras I tried this code from the hetero-nn example:
```
pipeline = PipeLine().set_initiator(role='guest', party_id=guest).set_roles(guest=guest, host=host)

reader_0 = Reader(name="reader_0")
reader_0.get_party_instance(role='guest', party_id=guest).component_param(table=guest_train_data)
reader_0.get_party_instance(role='host', party_id=host).component_param(table=host_train_data)

dataio_0 = DataIO(name="dataio_0")
dataio_0.get_party_instance(role='guest', party_id=guest).component_param(with_label=True)
dataio_0.get_party_instance(role='host', party_id=host).component_param(with_label=False)

intersection_0 = Intersection(name="intersection_0")

hetero_nn_0 = HeteroNN(name="hetero_nn_0", epochs=100,
                       interactive_layer_lr=0.15, batch_size=-1, early_stop="diff")

guest_nn_0 = hetero_nn_0.get_party_instance(role='guest', party_id=guest)
guest_nn_0.add_bottom_model(Dense(units=3, input_shape=(10,), activation="relu",
                                  kernel_initializer=initializers.Constant(value=1)))
guest_nn_0.set_interactve_layer(Dense(units=2, input_shape=(3,),
                                      kernel_initializer=initializers.Constant(value=1)))
guest_nn_0.add_top_model(Dense(units=1, input_shape=(2,), activation="sigmoid",
                               kernel_initializer=initializers.Constant(value=1)))

host_nn_0 = hetero_nn_0.get_party_instance(role='host', party_id=host)
host_nn_0.add_bottom_model(Dense(units=3, input_shape=(10,), activation="relu",
                                 kernel_initializer=initializers.Constant(value=1)))
host_nn_0.set_interactve_layer(Dense(units=2, input_shape=(3,),
                                     kernel_initializer=initializers.Constant(value=1)))
hetero_nn_0.compile(optimizer=optimizers.SGD(lr=0.15), metrics=["AUC"], loss="binary_crossentropy")

hetero_nn_1 = HeteroNN(name="hetero_nn_1")

evaluation_0 = Evaluation(name="evaluation_0")

pipeline.add_component(reader_0)
pipeline.add_component(dataio_0, data=Data(data=reader_0.output.data))
pipeline.add_component(intersection_0, data=Data(data=dataio_0.output.data))
pipeline.add_component(hetero_nn_0, data=Data(train_data=intersection_0.output.data))
pipeline.add_component(hetero_nn_1, data=Data(test_data=intersection_0.output.data),
                       model=Model(model=hetero_nn_0.output.model))
pipeline.add_component(evaluation_0, data=Data(data=hetero_nn_0.output.data))

pipeline.compile()

job_parameters = JobParameters(backend=backend, work_mode=work_mode)
pipeline.fit(job_parameters)

print(hetero_nn_0.get_config(roles={"guest": [guest],
                                    "host": [host]}))
print(pipeline.get_component("hetero_nn_0").get_summary())
```
As a result I got `ValueError`:
```
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_13/4044005682.py in <module>
     42 guest_nn_0 = hetero_nn_0.get_party_instance(role='guest', party_id=guest)
     43 guest_nn_0.add_bottom_model(Dense(units=3, input_shape=(10,), activation="relu",
---> 44                                   kernel_initializer=initializers.Constant(value=1)))
     45 guest_nn_0.set_interactve_layer(Dense(units=2, input_shape=(2,),
     46                                       kernel_initializer=initializers.Constant(value=1)))

/usr/local/lib/python3.7/site-packages/pipeline/component/hetero_nn.py in add_bottom_model(self, layer)
     63             setattr(self, "_bottom_nn_model", Sequential())
     64 
---> 65         self._bottom_nn_model.add(layer)
     66 
     67     def set_interactve_layer(self, layer):

/usr/local/lib/python3.7/site-packages/pipeline/component/nn/models/sequantial.py in add(self, layer)
     33             layer_type = "pytorch"
     34         else:
---> 35             raise ValueError("Layer type {} not support yet".format(type(layer)))
     36 
     37         self._add_layer(layer, layer_type)

ValueError: Layer type <class 'keras.layers.core.Dense'> not support yet
```
I guess Keras base layer cannot be used with `isinstance`:
```
from tensorflow.keras.layers import Dense
from tensorflow.python.keras.engine.base_layer import Layer
d = Dense(2)
isinstance(d, Layer)

Out:  False
```

2. Same code I tried with PyTorch:
```
hetero_nn_0 = HeteroNN(name="hetero_nn_0", epochs=100,
                       interactive_layer_lr=0.15, batch_size=-1, early_stop="diff")

guest_nn_0 = hetero_nn_0.get_party_instance(role='guest', party_id=guest)
guest_nn_0.add_bottom_model(Linear(10, 3))
guest_nn_0.set_interactve_layer(Linear(3, 2))
guest_nn_0.add_top_model(Linear(2, 1))

host_nn_0 = hetero_nn_0.get_party_instance(role='host', party_id=host)
host_nn_0.add_bottom_model(Linear(10, 3))
host_nn_0.set_interactve_layer(Linear(3, 2))

hetero_nn_0.compile(optimizer=SGD(lr=0.01, momentum=0.9), metrics=["AUC"], loss="binary_crossentropy")
```
And got the `AttributeError` as well:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_13/3103572728.py in <module>
     44 
     45 guest_nn_0 = hetero_nn_0.get_party_instance(role='guest', party_id=guest)
---> 46 guest_nn_0.add_bottom_model(Linear(10, 3))
     47 guest_nn_0.set_interactve_layer(Linear(3, 2))
     48 guest_nn_0.add_top_model(Linear(2, 1))

/usr/local/lib/python3.7/site-packages/pipeline/component/hetero_nn.py in add_bottom_model(self, layer)
     63             setattr(self, "_bottom_nn_model", Sequential())
     64 
---> 65         self._bottom_nn_model.add(layer)
     66 
     67     def set_interactve_layer(self, layer):

/usr/local/lib/python3.7/site-packages/pipeline/component/nn/models/sequantial.py in add(self, layer)
     35             raise ValueError("Layer type {} not support yet".format(type(layer)))
     36 
---> 37         self._add_layer(layer, layer_type)
     38 
     39     def _add_layer(self, layer, layer_type):

/usr/local/lib/python3.7/site-packages/pipeline/component/nn/models/sequantial.py in _add_layer(self, layer, layer_type)
     43 
     44         if self.__config_type == layer_type:
---> 45             self._model.add(layer)
     46             self.__config_type = layer_type
     47         else:

AttributeError: 'SequentialModel' object has no attribute 'add'
```

3. Moreover, I tried [mnist example](https://github.com/FederatedAI/FATE/tree/master/examples/dsl/v2/homo_nn/mnist_demo) as homo-nn with CLI and got `ModuleNotFoundError` in the FATE-Board:
```
1    [ERROR] [2021-11-03 08:39:51,898] [64738:140716695897920] - task_executor.py[line:179]: No module named 'dataclasses'
2    Traceback (most recent call last):
3      File "./fate/python/fate_flow/operation/task_executor.py", line 154, in run_task
4        run_object.run(component_parameters_on_party, task_run_args)
5      File "./fate/python/federatedml/model_base.py", line 101, in run
6        this_data_output = func(*params)
7      File "./fate/python/federatedml/nn/homo_nn/enter_point.py", line 109, in fit
8        from federatedml.nn.homo_nn._torch import build_trainer
9      File "./fate/python/federatedml/nn/homo_nn/_torch.py", line 24, in <module>
10        import pytorch_lightning as pl
11     File "/opt/app-root/lib/python3.6/site-packages/pytorch_lightning/__init__.py", line 21, in <module>
12       from pytorch_lightning.callbacks import Callback  # noqa: E402
13     File "/opt/app-root/lib/python3.6/site-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
14       from pytorch_lightning.callbacks.stochastic_weight_avg import StochasticWeightAveraging
15     File "/opt/app-root/lib/python3.6/site-packages/pytorch_lightning/callbacks/stochastic_weight_avg.py", line 26, in <module>
16       from pytorch_lightning.trainer.optimizers import _get_default_scheduler_config
17     File "/opt/app-root/lib/python3.6/site-packages/pytorch_lightning/trainer/__init__.py", line 18, in <module>
18       from pytorch_lightning.trainer.trainer import Trainer
19     File "/opt/app-root/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 26, in <module>
20       from pytorch_lightning.accelerators import Accelerator
21     File "/opt/app-root/lib/python3.6/site-packages/pytorch_lightning/accelerators/__init__.py", line 13, in <module>
22       from pytorch_lightning.accelerators.accelerator import Accelerator  # noqa F401
23     File "/opt/app-root/lib/python3.6/site-packages/pytorch_lightning/accelerators/accelerator.py", line 25, in <module>
24       from pytorch_lightning.plugins.precision import ApexMixedPrecisionPlugin, NativeMixedPrecisionPlugin, PrecisionPlugin
25     File "/opt/app-root/lib/python3.6/site-packages/pytorch_lightning/plugins/__init__.py", line 2, in <module>
26       from pytorch_lightning.plugins.plugins_registry import (  # noqa: F401
27     File "/opt/app-root/lib/python3.6/site-packages/pytorch_lightning/plugins/plugins_registry.py", line 21, in <module>
28       from pytorch_lightning.plugins.training_type.training_type_plugin import TrainingTypePlugin
29     File "/opt/app-root/lib/python3.6/site-packages/pytorch_lightning/plugins/training_type/__init__.py", line 3, in <module>
30       from pytorch_lightning.plugins.training_type.ddp_spawn import DDPSpawnPlugin  # noqa: F401
31     File "/opt/app-root/lib/python3.6/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 30, in <module>
32       from pytorch_lightning.trainer.states import TrainerFn
33     File "/opt/app-root/lib/python3.6/site-packages/pytorch_lightning/trainer/states.py", line 14, in <module>
34       from dataclasses import dataclass
35   ModuleNotFoundError: No module named 'dataclasses'
```
Probably it occurs due to incompatibility and It [requires](https://github.com/facebookresearch/pytorch3d/issues/31) to update Python at least to 3.7

**Comment by owlet42** [comment]
The third question has been solved in the new version. You may get the answers to the first two questions in the FATE project. You can issue in the [FATE](https://github.com/FederatedAI/FATE/issues) project.
