### ISSUE TITLE
run min_test_task get error on kubeFATE

### ISSUE THREAD

**Issue by JasonBian** [FederatedAI/KubeFATE#529]
using kubefate to deploy fate cluster
* FATE:1.7.0
* kubefate commandLine version=v1.4.2
* kubefate service version=v1.4.2

after cluster deployed,I submit the min_test_task,I got error:

python run_task.py -gid 10000 -hid 9999 -aid 9999

[2022-02-21 08:34:58] Start task: job submit

{
    "data": {
        "board_url": "http://fateboard:8080/index.html#/dashboard?job_id=202202210834589399880&role=guest&party_id=10000",
        "code": 0,
        "dsl_path": "/data/projects/fate/fateflow/jobs/202202210834589399880/job_dsl.json",
        "job_id": "202202210834589399880",
        "logs_directory": "/data/projects/fate/fateflow/logs/202202210834589399880",
        "message": "success",
        "model_info": {
            "model_id": "arbiter-9999#guest-10000#host-9999#model",
            "model_version": "202202210834589399880"
        },
        "pipeline_dsl_path": "/data/projects/fate/fateflow/jobs/202202210834589399880/pipeline_dsl.json",
        "runtime_conf_on_party_path": "/data/projects/fate/fateflow/jobs/202202210834589399880/guest/10000/job_runtime_on_party_conf.json",
        "runtime_conf_path": "/data/projects/fate/fateflow/jobs/202202210834589399880/job_runtime_conf.json",
        "train_runtime_conf_path": "/data/projects/fate/fateflow/jobs/202202210834589399880/train_runtime_conf.json"
    },
    "jobId": "202202210834589399880",
    "retcode": 0,
    "retmsg": "success"
}
[2022-02-21 08:35:07] Start task: job query

[2022-02-21 08:35:07] Current task status: waiting

[2022-02-21 08:35:17] Start task: job query

[2022-02-21 08:35:17] Current task status: running

[2022-02-21 08:35:27] Start task: job query

[2022-02-21 08:35:27] Current task status: running

[2022-02-21 08:35:37] Start task: job query

[2022-02-21 08:35:37] Current task status: running

[2022-02-21 08:35:47] Start task: job query

[2022-02-21 08:35:47] Current task status: running

[2022-02-21 08:35:57] Start task: job query

[2022-02-21 08:35:57] Current task status: running

[2022-02-21 08:36:07] Start task: job query

[2022-02-21 08:36:07] Current task status: running

[2022-02-21 08:36:17] Start task: job query

[2022-02-21 08:36:17] Current task status: failed

fate_flow_schedule_error.log:
[ERROR] [2022-02-21 08:35:09,646] [202202210834589399880] [29:139870888470272] - [federated_scheduler.task_command] [line:246]: failed to execute federated task reader_0 command(status/running) detail:
{'guest': {'10000': {'retcode': 10, 'retmsg': 'update job status does not take effect'}}, 'host': {'9999': {'retcode': 0, 'retmsg': 'success'}}}
[ERROR] [2022-02-21 08:35:42,123] [202202210834589399880] [29:139870888470272] - [federated_scheduler.task_command] [line:246]: failed to execute federated task reader_1 command(status/running) detail:
{'guest': {'10000': {'retcode': 10, 'retmsg': 'update job status does not take effect'}}, 'host': {'9999': {'retcode': 0, 'retmsg': 'success'}}}

fate_flow_schedule.log:
[INFO] [2022-02-21 08:35:14,670] [202202210834589399880] [29:139870888470272] - [resource_manager.resource_for_task] [line:293]: cores_per_task:4, memory_per_task:0
[WARNING] [2022-02-21 08:35:14,676] [202202210834589399880] [29:139870888470272] - [resource_manager.resource_for_task] [line:315]: task 202202210834589399880_reader_1 0 ResourceOperation.APPLY resource failed
[INFO] [2022-02-21 08:35:14,677] [202202210834589399880] [29:139870888470272] - [task_scheduler.schedule] [line:83]: task 202202210834589399880_reader_1 can not apply resource, wait for the next round of scheduling

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/psutil/__init__.py", line 354, in _init
    self.create_time()
  File "/opt/app-root/lib/python3.6/site-packages/psutil/__init__.py", line 710, in create_time
    self._create_time = self._proc.create_time()
  File "/opt/app-root/lib/python3.6/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/psutil/_pslinux.py", line 1788, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
  File "/opt/app-root/lib/python3.6/site-packages/psutil/_pslinux.py", line 1583, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=567)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/projects/fate/fateflow/python/fate_flow/manager/worker_manager.py", line 293, in kill_task_all_workers
    cls.kill_worker(worker_info)
  File "/data/projects/fate/fateflow/python/fate_flow/manager/worker_manager.py", line 303, in kill_worker
    process = psutil.Process(worker_info.f_run_pid)
  File "/opt/app-root/lib/python3.6/site-packages/psutil/__init__.py", line 326, in __init__
    self._init(pid)
  File "/opt/app-root/lib/python3.6/site-packages/psutil/__init__.py", line 367, in _init
    raise NoSuchProcess(pid, None, msg)
psutil.NoSuchProcess: psutil.NoSuchProcess no process found with pid 567

**Comment by JasonBian** [comment]
I forget the pre upload steps
