### ISSUE TITLE
spark_rabbitmq部署上传100M文件报hdfs错误

### ISSUE THREAD

**Issue by xiahaijiao** [FederatedAI/KubeFATE#530]
`
197
[ERROR] [2022-02-22 10:04:47,273] [202202221004170327460] [56660:140659623761728] - [task_executor._run_] [line:243]: HDFS Flush failed, errno: 255 (Unknown error 255) Please check that you are connecting to the correct HDFS RPC port
198
Traceback (most recent call last):
199
  File "./fate/fate/python/fate_arch/storage/hdfs/_table.py", line 77, in _put_all
200
    writer.write(hdfs_utils.serialize(k, v))
201
  File "pyarrow/io.pxi", line 283, in pyarrow.lib.NativeFile.write
202
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
203
OSError: HDFS Write failed, errno: 255 (Unknown error 255) Please check that you are connecting to the correct HDFS RPC port
204
205
During handling of the above exception, another exception occurred:
206
207
Traceback (most recent call last):
208
  File "pyarrow/io.pxi", line 262, in pyarrow.lib.NativeFile.flush
209
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
210
OSError: HDFS Flush failed, errno: 255 (Unknown error 255) Please check that you are connecting to the correct HDFS RPC port
211
212
During handling of the above exception, another exception occurred:
213

`

**Comment by JingChen23** [comment]
This is duplicated with #579
As we already have some discussions there, close this one.
