### ISSUE TITLE
When I deploy FATE using the examples file, I get an error running the task: '>=' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by owlet42** [FederatedAI/KubeFATE#557]
**What deployment mode you are use?  **
Kuberentes.

**What KubeFATE and FATE version you are using?  **
KubeFATE v1.7.2
FATE v1.7.2
kubefate v1.4.3

**What happen?**
When I deploy FATE using the examples file, I get an error running the task: '>=' not supported between instances of 'int' and 'str'

**Tasks**

- [x] #558
- [x] Fix in v1.8.0

**Comment by owlet42** [comment]
A temporary solution is to configure the value of `python.logLevel`, for example:
```yaml
$ cat cluster.yaml
...
python:
...
  logLevel: INFO
...
```

**Comment by LaynePeng** [comment]
@owlet42 can you describe a bit more how to reproduce this bug? For example,  not using the default values or something...

**Comment by owlet42** [comment]
How to reproduce the bug:
Use k8s to deploy KubeFATE, use this cluster.yaml to deploy FATE
```yaml
name: fate-9999
namespace: fate-9999
chartName: fate
chartVersion: v1.7.2
partyId: 9999
registry: ""
imageTag: 1.7.2-release
pullPolicy: 
imagePullSecrets: 
- name: myregistrykey
persistence: false
istio:
  enabled: false
podSecurityPolicy:
  enabled: false
modules:
  - rollsite
  - clustermanager
  - nodemanager
  - mysql
  - python
  - fateboard
  - client

backend: eggroll

ingress:
  fateboard: 
    annotations:
      kubernetes.io/ingress.class: "nginx"
    hosts:
    - name: party9999.fateboard.example.com
  client:  
    annotations:
      kubernetes.io/ingress.class: "nginx"
    hosts:
    - name: party9999.notebook.example.com
 
python:
  type: NodePort
  httpNodePort: 30097
  grpcNodePort: 30092

```
Using the FATE deployed by the above yaml, execute a FATE task, such as upload data:
```bash
$ kubectl exec -it svc/notebook -n fate-9999 -- bash
# flow data upload -c examples/dsl/v2/upload/upload_conf.json
```
View the task log of FATE just now
```bash
$ kubectl exec -it svc/fateflow -n fate-9999 -- bash
# cat fateflow/logs/202203160930298606490/local/0/upload_0/stat.log
```
You will get this error:
```
[ERROR] [2022-03-16 09:30:32,855] [202203160930298606490] [54:140243045480256] - [base_worker.run] [line:110]: '>=' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File "/data/projects/fate/fateflow/python/fate_flow/worker/base_worker.py", line 94, in run
    append_to_parent_log=True, force=True)
  File "/data/projects/fate/fate/python/fate_arch/common/log.py", line 82, in set_directory
    LoggerFactory.assemble_global_handler(logger)
  File "/data/projects/fate/fate/python/fate_arch/common/log.py", line 177, in assemble_global_handler
    if level >= LoggerFactory.LEVEL:
TypeError: '>=' not supported between instances of 'int' and 'str'
[ERROR] [2022-03-16 09:30:32,856] [202203160930298606490] [54:140243045480256] - [base_worker.run] [line:115]: 'task_id'
Traceback (most recent call last):
  File "/data/projects/fate/fateflow/python/fate_flow/worker/base_worker.py", line 94, in run
    append_to_parent_log=True, force=True)
  File "/data/projects/fate/fate/python/fate_arch/common/log.py", line 82, in set_directory
    LoggerFactory.assemble_global_handler(logger)
  File "/data/projects/fate/fate/python/fate_arch/common/log.py", line 177, in assemble_global_handler
    if level >= LoggerFactory.LEVEL:
TypeError: '>=' not supported between instances of 'int' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/projects/fate/fateflow/python/fate_flow/worker/base_worker.py", line 113, in run
    self._handle_exception()
  File "/data/projects/fate/fateflow/python/fate_flow/worker/task_base_worker.py", line 115, in _handle_exception
    self.report_task_info_to_driver()
  File "/data/projects/fate/fateflow/python/fate_flow/worker/task_base_worker.py", line 120, in report_task_info_to_driver
    self.report_info["task_id"],
KeyError: 'task_id'
[INFO] [2022-03-16 09:30:32,856] [202203160930298606490] [54:140243045480256] - [base_worker.run] [line:122]: worker TaskExecutor, process role: ProcessRole.WORKER, pid: 54, elapsed: 3 ms
```
