### ISSUE TITLE
can not upload file over 100M with spark backend

### ISSUE THREAD

**Issue by majorinche** [FederatedAI/KubeFATE#600]
kubefate-1.7.2

cannot upload file with size over 100MB, and report error like following:

[task_executor._run_] [line:243]: HDFS Flush failed, errno: 255 (Unknown error 255) Please check that you are connecting to the correct HDFS RPC port
Traceback (most recent call last):
  File "/data/projects/fate/fate/python/fate_arch/storage/hdfs/_table.py", line 77, in _put_all
    writer.write(hdfs_utils.serialize(k, v))
  File "pyarrow/io.pxi", line 283, in pyarrow.lib.NativeFile.write
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
OSError: HDFS Write failed, errno: 255 (Unknown error 255) Please check that you are connecting to the correct HDFS RPC port

check with non-container environment, upload function is ok.

please help to check and fix.

thanks
majorin

**Comment by LaynePeng** [comment]
What volume type you are using?

**Comment by stone-wlg** [comment]
i have the same issue before, you could try to scale datanode pod to 3. hope useful to you

**Comment by JingChen23** [comment]
@majorinche  If you are using docker-compose, you can follow the workaround on #579

**Comment by LaynePeng** [comment]
@stone-wlg it works, thanks for the information.

**Comment by songsong124** [comment]
我部署了单机版spark on yarn+pulsar 方式：也出现如下错误：
Traceback (most recent call last):
  File "/data/projects/fate/fateflow/python/fate_flow/worker/task_executor.py", line 195, in _run_
    cpn_output = run_object.run(cpn_input)
  File "/data/projects/fate/fateflow/python/fate_flow/components/_base.py", line 149, in run
    method(cpn_input)
  File "/data/projects/fate/fateflow/python/fate_flow/components/upload.py", line 203, in _run
    data_table_count = self.save_data_table(job_id, name, namespace, storage_engine, head)
  File "/data/projects/fate/fateflow/python/fate_flow/components/upload.py", line 233, in save_data_table
    self.upload_file(input_file, head, job_id, input_feature_count)
  File "/data/projects/fate/fateflow/python/fate_flow/components/upload.py", line 338, in upload_file
    table.put_all(data)
  File "/data/projects/fate/fate/python/fate_arch/storage/_table.py", line 122, in put_all
    self._put_all(kv_list, **kwargs)
  File "/data/projects/fate/fate/python/fate_arch/storage/hdfs/_table.py", line 84, in _put_all
    counter = counter + 1
  File "pyarrow/io.pxi", line 132, in pyarrow.lib.NativeFile.close
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
