### ISSUE TITLE
error when starting up docker container

### ISSUE THREAD

**Issue by cometta** [FederatedAI/KubeFATE#74]
If i down all docker containers and restart all containers, i get below error. 

```
File "fate_flow_server.py", line 91, in <module>
python_1        | Traceback (most recent call last):
python_1        |   File "fate_flow_server.py", line 93, in <module>
python_1        |     session.init(mode=RuntimeConfig.WORK_MODE, backend=Backend.EGGROLL)
python_1        |   File "/data/projects/fate/python/arch/api/session.py", line 52, in init
python_1        |     session = build_session(job_id=job_id, work_mode=mode, backend=backend)
python_1        |   File "/data/projects/fate/python/arch/api/table/session.py", line 38, in build_session
python_1        |     session = session_impl.FateSessionImpl(eggroll_session, work_mode, persistent_engine)
python_1        |   File "/data/projects/fate/python/arch/api/table/eggroll/session_impl.py", line 33, in __init__
python_1        |     self._eggroll = eggroll_util.build_eggroll_runtime(work_mode=work_mode, eggroll_session=eggroll_session)
python_1        |   File "/data/projects/fate/python/arch/api/table/eggroll_util.py", line 44, in build_eggroll_runtime
python_1        |     return eggroll_init(eggroll_session)
python_1        |   File "/data/projects/fate/python/eggroll/api/cluster/eggroll.py", line 79, in eggroll_init
python_1        |     eggroll_runtime = _EggRoll(eggroll_session=eggroll_session)
python_1        |   File "/data/projects/fate/python/eggroll/api/cluster/eggroll.py", line 364, in __init__
python_1        |     self.session_stub.getOrCreateSession(self.eggroll_session.to_protobuf())
python_1        |   File "/data/projects/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 533, in __call__
python_1        |     return _end_unary_response_blocking(state, call, False, None)
python_1        |   File "/data/projects/python/venv/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
python_1        |     raise _Rendezvous(state, None, None, deadline)
python_1        | grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
python_1        | 	status = StatusCode.UNAVAILABLE
python_1        | 	details = "Connect Failed"

```

**Comment by LaynePeng** [comment]
按下面步骤检查：1. server.conf的配置；2. Egg的容器是不是正常起来；3. python container到Egg的container中间玩咯是否有问题。

**Comment by cometta** [comment]
can close this ticket, it was old issue
