### ISSUE TITLE
docker-compose部署，一方单边测试成功，一方单边测试失败，报错：java.lang.NoSuchMethodError: com.google.protobuf.GeneratedMessageV3.isStringEmpty(Ljava/lang/Object;)Z\\n\\tat com.webank.ai.eggroll.api.networking.proxy.Proxy$Task.getSerializedSize

### ISSUE THREAD

**Issue by HelloJeremy** [FederatedAI/KubeFATE#766]
Caused by: java.lang.NoSuchMethodError: com.google.protobuf.GeneratedMessageV3.isStringEmpty(Ljava/lang/Object;)Z
	at com.webank.ai.eggroll.api.networking.proxy.Proxy$Task.getSerializedSize(Proxy.java:1120) ~[eggroll-core-2.4.5.jar:?]
	at com.google.protobuf.CodedOutputStream.computeMessageSizeNoTag(CodedOutputStream.java:877) ~[protobuf-java-3.16.1.jar:?]
	at com.google.protobuf.CodedOutputStream.computeMessageSize(CodedOutputStream.java:661) ~[protobuf-java-3.16.1.jar:?]
	at com.webank.ai.eggroll.api.networking.proxy.Proxy$Metadata.getSerializedSize(Proxy.java:4893) ~[eggroll-core-2.4.5.jar:?]
	at com.google.protobuf.CodedOutputStream.computeMessageSizeNoTag(CodedOutputStream.java:877) ~[protobuf-java-3.16.1.jar:?]
	at com.google.protobuf.CodedOutputStream.computeMessageSize(CodedOutputStream.java:661) ~[protobuf-java-3.16.1.jar:?]
	at com.webank.ai.eggroll.api.networking.proxy.Proxy$Packet.getSerializedSize(Proxy.java:7465) ~[eggroll-core-2.4.5.jar:?]
	at io.grpc.protobuf.lite.ProtoInputStream.available(ProtoInputStream.java:108) ~[grpc-protobuf-lite-1.27.2.jar:1.27.2]
	at io.grpc.internal.MessageFramer.getKnownLength(MessageFramer.java:205) ~[grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:137) ~[grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:53) ~[grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37) ~[grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.internal.RetriableStream$1SendMessageEntry.runWith(RetriableStream.java:490) ~[grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.internal.RetriableStream.delayOrExecute(RetriableStream.java:467) ~[grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.internal.RetriableStream.sendMessage(RetriableStream.java:494) ~[grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.internal.ClientCallImpl.sendMessageInternal(ClientCallImpl.java:534) ~[grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:520) ~[grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:289) ~[grpc-stub-1.27.2.jar:1.27.2]
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:196) ~[grpc-stub-1.27.2.jar:1.27.2]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:130) ~[grpc-stub-1.27.2.jar:1.27.2]
	at com.webank.ai.eggroll.api.networking.proxy.DataTransferServiceGrpc$DataTransferServiceBlockingStub.unaryCall(DataTransferServiceGrpc.java:348) ~[eggroll-core-2.4.5.jar:?]
	at com.webank.eggroll.rollsite.EggSiteServicer.unaryCall(EggSiteServicer.scala:138) [eggroll-roll-site-2.4.5.jar:?]
	... 13 more

**Comment by JingChen23** [comment]
Cou you please check the status of the docker containers of your failed party?

**Comment by HelloJeremy** [comment]
> Cou you please check the status of the docker containers of your failed party?

Container status is normal of my failed party.Below is the running status of my failed party.
![微信图片_20220926115358](https://user-images.githubusercontent.com/23650729/192406894-707310ae-cd48-4cc5-8298-94549c50a6ed.png)
