### ISSUE TITLE
problem with 1.9.0-release images

### ISSUE THREAD

**Issue by asdfsx** [FederatedAI/KubeFATE#783]
Deploy fate 1.9.0-release using kubefate. When executing `flow test toy -gid 10000 -hid 10000`, got following error in pod`rollsite`
```
[DEBUG][120718][2022-10-21 02:10:50,777][routine-executor-1,pid:1,tid:11][c.w.e.r.Router:111] - refreshing route table at path=conf/route_table/route_table.json
Exception in thread "grpc-server-9370-0" java.lang.AbstractMethodError: io.grpc.netty.shaded.io.grpc.netty.NettyServerStream$Sink.request(I)V
	at io.grpc.internal.AbstractServerStream.request(AbstractServerStream.java:106)
	at io.grpc.internal.ServerCallImpl.request(ServerCallImpl.java:90)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler.startCall(ServerCalls.java:132)
	at io.grpc.Contexts.interceptCall(Contexts.java:52)
	at com.webank.eggroll.rollsite.AddrAuthServerInterceptor.interceptCall(WhiteList.scala:49)
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:244)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:648)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startCall(ServerImpl.java:626)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$1900(ServerImpl.java:417)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInternal(ServerImpl.java:556)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInContext(ServerImpl.java:531)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```
Some one said the problem is caused by `grpc-core` version conflict. So I rebuild the eggroll image.

The problem solved by using the eggroll image build by my own. Then I compare the 2 image and found that, the image you build contain the following jar files, you can find multiple version jar files.
```
[root@62397cfabd7a lib]# pwd
/data/projects/fate/eggroll/lib
[root@62397cfabd7a lib]# ls *grpc* -al
-rw-r--r-- 1 root root    6989 Aug 31 13:43 flatbuffers-java-grpc-1.10.0.jar
-rw-r--r-- 1 root root  223975 Aug 16 06:39 grpc-api-1.27.2.jar
-rw-r--r-- 1 root root  225287 Aug 31 13:43 grpc-api-1.31.2.jar
-rw-r--r-- 1 root root   30073 Aug 16 06:39 grpc-context-1.27.2.jar
-rw-r--r-- 1 root root   30570 Aug 31 13:43 grpc-context-1.31.2.jar
-rw-r--r-- 1 root root  678360 Aug 16 06:39 grpc-core-1.27.2.jar
-rw-r--r-- 1 root root  609094 Aug 31 13:43 grpc-core-1.31.2.jar
-rw-r--r-- 1 root root 7028146 Aug 16 06:39 grpc-netty-shaded-1.27.2.jar
-rw-r--r-- 1 root root 7068403 Aug 31 13:43 grpc-netty-shaded-1.31.2.jar
-rw-r--r-- 1 root root    5179 Aug 16 06:39 grpc-protobuf-1.27.2.jar
-rw-r--r-- 1 root root    5179 Aug 31 13:43 grpc-protobuf-1.31.2.jar
-rw-r--r-- 1 root root    7629 Aug 16 06:39 grpc-protobuf-lite-1.27.2.jar
-rw-r--r-- 1 root root    7629 Aug 31 13:43 grpc-protobuf-lite-1.31.2.jar
-rw-r--r-- 1 root root   47566 Aug 16 06:39 grpc-stub-1.27.2.jar
-rw-r--r-- 1 root root   49585 Aug 31 13:43 grpc-stub-1.31.2.jar
```

And the images I build contain following jar files
```
root@450d5ce94175:/data/projects/fate/eggroll/lib# ls *grpc* -al
-rw-r--r-- 1 root root    6989 Oct 21 02:09 flatbuffers-java-grpc-1.10.0.jar
-rw-r--r-- 1 root root  225287 Oct 21 02:09 grpc-api-1.31.2.jar
-rw-r--r-- 1 root root   30570 Oct 21 02:09 grpc-context-1.31.2.jar
-rw-r--r-- 1 root root  609094 Oct 21 02:09 grpc-core-1.31.2.jar
-rw-r--r-- 1 root root 7068403 Oct 21 02:09 grpc-netty-shaded-1.31.2.jar
-rw-r--r-- 1 root root    5179 Oct 21 02:09 grpc-protobuf-1.31.2.jar
-rw-r--r-- 1 root root    7629 Oct 21 02:09 grpc-protobuf-lite-1.31.2.jar
-rw-r--r-- 1 root root   49585 Oct 21 02:09 grpc-stub-1.31.2.jar
```

Maybe the official images should be rebuilt and updated

@LaynePeng 
@jat001

**Comment by LaynePeng** [comment]
Thanks for pointing out the problem, we will double-check it. @JingChen23

**Comment by JingChen23** [comment]
@asdfsx 
1. You used k8s or docker-compose?
2. Though you got the error msg, did you job succeed finally?

**Comment by asdfsx** [comment]
@JingChen23 
1. I use k8s 1.20
2. No, the `flow` command also return error
    ```
    root@client-0:/data/projects/fate# flow test toy  -gid 10000 -hid 10000
    {
        "jobId": "202210210210515842060",
        "retcode": 103,
        "retmsg": "Traceback (most recent call last):\n  File \"/data/projects/fate/fateflow/python/fate_flow/scheduler/dag_scheduler.py\", line 142, in submit\n    raise Exception(\"create job failed\", response)\nException: ('create job failed', {'guest': {10000: {'retcode': <RetCode.FEDERATED_ERROR: 104>, 'retmsg': 'Federated schedule error, <_InactiveRpcError of RPC that terminated with:\\n\\tstatus = StatusCode.UNKNOWN\\n\\tdetails = \"\"\\n\\tdebug_error_string = \"{\"created\":\"@1666318257.691411366\",\"description\":\"Error received from peer ipv4:10.109.23.100:9370\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":952,\"grpc_message\":\"\",\"grpc_status\":2}\"\\n>'}}, 'host': {10000: {'retcode': <RetCode.FEDERATED_ERROR: 104>, 'retmsg': 'Federated schedule error, <_InactiveRpcError of RPC that terminated with:\\n\\tstatus = StatusCode.UNKNOWN\\n\\tdetails = \"\"\\n\\tdebug_error_string = \"{\"created\":\"@1666318263.714283934\",\"description\":\"Error received from peer ipv4:10.109.23.100:9370\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":952,\"grpc_message\":\"\",\"grpc_status\":2}\"\\n>'}}})\n"
    }
    ```
3. I use `fate-builder` to build the image

**Comment by JingChen23** [comment]
Thanks @asdfsx , I have double checked and find that you are right. I have updated the image on dockerhub and 163.
