### ISSUE TITLE
使用minikube部署kubefate出现问题

### ISSUE THREAD

**Issue by KAgBMan** [FederatedAI/KubeFATE#789]
您好，我在云服务器上部署kubefate的时候出现了python pod部署错误的情况，如下图
![image](https://user-images.githubusercontent.com/22344179/199381865-a994f5e0-84fa-407f-b2dd-cf3b2790efeb.png)
查看日志后发现是拒绝连接，请问这个该怎么解决？
![image](https://user-images.githubusercontent.com/22344179/199381993-453bd033-ae2a-4b21-8f84-53c3a27210f8.png)

**Comment by JingChen23** [comment]
run `kubectl logs <python-containerid> -n fate-9999`

**Comment by KAgBMan** [comment]
error: a container name must be specified for pod python-7465595dd5-hb57b, choose one of: [python fateboard] or one of the init containers: [ping-mysql]

**Comment by KAgBMan** [comment]
@JingChen23 
error: a container name must be specified for pod python-7465595dd5-hb57b, choose one of: [python fateboard] or one of the init containers: [ping-mysql]

**Comment by KAgBMan** [comment]
@JingChen23 
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/handlers.py", line 73, in emit
    logging.FileHandler.emit(self, record)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1071, in emit
    self.stream = self._open()
  File "/data/projects/fate/fate/python/fate_arch/common/log.py", line 211, in _open
    rtv = TimedRotatingFileHandler._open(self)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 29] Illegal seek
Call stack:
  File "fateflow/python/fate_flow/fate_flow_server.py", line 72, in <module>
    ConfigManager.load()
  File "/data/projects/fate/fateflow/python/fate_flow/db/config_manager.py", line 29, in load
    ResourceManager.initialize()
  File "/data/projects/fate/fateflow/python/fate_flow/manager/resource_manager.py", line 40, in initialize
    cls.register_engine(engine_type=engine_type, engine_name=engine_name, engine_entrance=engine_group_map[engine_type][engine_name], engine_config=engine_config)
  File "/opt/app-root/lib/python3.6/site-packages/peewee.py", line 394, in inner
    return fn(*args, **kwargs)
  File "/data/projects/fate/fateflow/python/fate_flow/manager/resource_manager.py", line 64, in register_engine
    stat_logger.info(f"update {engine_type} engine {engine_name} {engine_entrance} registration information")
Message: 'update federation engine PULSAR fate_on_spark registration information'
Arguments: ()
Traceback (most recent call last):
  File "fateflow/python/fate_flow/fate_flow_server.py", line 81, in <module>
    ComponentRegistry.load()
  File "/data/projects/fate/fateflow/python/fate_flow/db/component_registry.py", line 35, in load
    component_registry = cls.get_from_db(file_utils.load_json_conf_real_time(FATE_FLOW_DEFAULT_COMPONENT_REGISTRY_PATH))
  File "/opt/app-root/lib/python3.6/site-packages/peewee.py", line 394, in inner
    return fn(*args, **kwargs)
  File "/data/projects/fate/fateflow/python/fate_flow/db/component_registry.py", line 179, in get_from_db
    for component_alias in component_registry["components"][module.f_component_name]["alias"]:
KeyError: 'datatransform'

**Comment by JingChen23** [comment]
1. What is your kubefate version and fate version?
2. Is this a fresh deployment or upgraded deployment?
3. Could you post your cluster.yaml file here? (need to hide the secret information by yourself)

**Comment by KAgBMan** [comment]
kubefate-version:v1.4.4
fate-version:v1.8.0
fresh deployment

```
name: fate-9999
namespace: fate-9999
chartName: fate
chartVersion: v1.8.0
partyId: 9999
registry: "hub.c.163.com/federatedai"
imageTag: "1.8.0-release"
pullPolicy:
imagePullSecrets:
- name: myregistrykey
persistence: false
istio:
  enabled: false
podSecurityPolicy:
  enabled: false
ingressClassName: nginx
modules:
  - rollsite
  - clustermanager
  - nodemanager
  - python
  - fateboard
  - client
 
backend: eggroll
externalMysqlIp: xx.xx.xx.xx
externalMysqlPort: 3306
externalMysqlDatabase: fate
externalMysqlUser: root
externalMysqlPassword: mpw
ingress:
  fateboard:
    hosts:
    - name: party9999.fateboard.example.com
  client:  
    hosts:
    - name: party9999.notebook.example.com
 
rollsite:
  type: NodePort
  nodePort: 30091
  partyList:
  - partyId: 10000
    partyIp: 172.31.0.18
    partyPort: 30101
 
python:
  type: NodePort
  httpNodePort: 30097
  grpcNodePort: 30092
  logLevel: INFO
 
servingIp: 172.31.0.18
servingPort: 30095
```

**Comment by KAgBMan** [comment]
@JingChen23 
这是使用的教程
https://blog.csdn.net/qq_32202885/article/details/125998028

**Comment by JingChen23** [comment]
Has the mysql been used before?
Especially be used by a FATE system whose version is < 1.8.0 ?

**Comment by KAgBMan** [comment]
@JingChen23 
我之前是按照教程中的方式添加mysql模块，
```
modules:
  - rollsite
  - clustermanager
  - nodemanager
  - python
  - fateboard
  - client
```
但是会报错
```
2022-11-03T02:50:09.354446Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.28) starting as process 1
2022-11-03T02:50:10.057618Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-11-03T02:51:09.424250Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mysqld: Table 'mysql.plugin' doesn't exist
2022-11-03T02:51:11.070816Z 0 [ERROR] [MY-010735] [Server] Could not open the mysql.plugin table. Please perform the MySQL upgrade procedure.
2022-11-03T02:51:11.071276Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
```
然后我就自己部署了一个mysql，新创建了一个fate数据库，然后把连接信息填写到cluster.yaml中，执行kubefate cluster install之后，我自己的mysql数据库中已经出现了表及数据
![image](https://user-images.githubusercontent.com/22344179/199639354-34b002fb-bee0-4e32-a1ee-e315d4dca5ea.png)

**Comment by JingChen23** [comment]
This could be a known issue, let's try to use FATE v1.9.0 to see if this can be reproduced.

**Comment by KAgBMan** [comment]
我已经把版本升级到了1.9.0（使用教程https://github.com/FederatedAI/KubeFATE/blob/master/docs/tutorials/Build_Two_Parties_FATE_Cluster_in_One_Linux_Machine_with_MiniKube_zh.md），并且使用了自带的mysql
执行kubefate cluster install之后mysql报错：mysql logs如下
```
2022-11-03 06:00:50+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.28-1debian10 started.
2022-11-03 06:00:50+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2022-11-03 06:00:50+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.28-1debian10 started.
2022-11-03T06:00:51.117016Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.28) starting as process 1
2022-11-03T06:00:51.236638Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-11-03T06:00:57.214549Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2022-11-03T06:00:57.221459Z 1 [ERROR] [MY-011096] [Server] No data dictionary version number found.
2022-11-03T06:00:57.221788Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
2022-11-03T06:00:57.222039Z 0 [ERROR] [MY-010119] [Server] Aborting
2022-11-03T06:00:57.812027Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.28)  MySQL Community Server - GPL.
```
pod describe 如下
```
  Normal   Started    2m46s (x3 over 6m24s)   kubelet, fate-01.novalocal  Started container mysql
  Warning  Unhealthy  2m41s (x14 over 6m20s)  kubelet, fate-01.novalocal  Startup probe failed: mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
  Warning  BackOff  2m38s                kubelet, fate-01.novalocal  Back-off restarting failed container
  Normal   Created  98s (x5 over 6m31s)  kubelet, fate-01.novalocal  Created container mysql
```
cluster.yaml如下
```
name: fate-9999
namespace: fate-9999
chartName: fate
chartVersion: v1.9.0
partyId: 9999
registry: "hub.c.163.com/federatedai"
pullPolicy:
imagePullSecrets: 
- name: myregistrykey
persistence: false
istio:
  enabled: false
podSecurityPolicy:
  enabled: false
ingressClassName: nginx
modules:
  - rollsite
  - clustermanager
  - nodemanager
  - mysql
  - python
  - fateboard
  - client

computing: Eggroll
federation: Eggroll
storage: Eggroll
algorithm: Basic
device: CPU

ingress:
  fateboard:
    hosts:
    - name: party9999.fateboard.example.com
  client:  
    hosts:
    - name: party9999.notebook.example.com

rollsite:
  type: NodePort
  nodePort: 30091
  partyList:
    - partyId: 10000
      partyIp: 172.31.0.30
      partyPort: 30101

python:
  type: NodePort
  httpNodePort: 30097
  grpcNodePort: 30092
  logLevel: INFO

servingIp: 172.31.0.30
servingPort: 30095
```

**Comment by JingChen23** [comment]
Your minikube is launched on what kind of machine, OS and version?

**Comment by KAgBMan** [comment]
浪潮云服务器
CentOS Linux release 7.8.2003 (Core)

**Comment by JingChen23** [comment]
Actually the problem is that you cannot launch mysql in your k8s.

I tried to help you find an answer but I didn't find anything.

I suggest do something like:

1. Search on stackoverflow, try to find some solutions.
2. Change the minikube version to a newer one, or change the k8s version to a newer one.
3. Change the host server, my verified centos version is CentOS Linux release 7.9.2009 (Core).

Because you have set `persistence: false`

The mysql should be a fresh start so definitely the problem has nothing to do with our helm chart.

**Comment by KAgBMan** [comment]
@JingChen23 
您好，我部署好了一个节点，但是集群依然显示creating，请问这是为什么？
![image](https://user-images.githubusercontent.com/22344179/199672401-1177d585-4a72-4a82-8ef6-de6006cc6b09.png)

**Comment by JingChen23** [comment]
`kubefate job describe <job uuid>`

You need to check the creat cluster job status.

**Comment by KAgBMan** [comment]
@JingChen23 
已经部署成功了，非常感谢，另外想问一下您有没有python容器下目录结构解析的相关文档？或者不使用jupyter进行测试的测试文档？

**Comment by JingChen23** [comment]
> @JingChen23 已经部署成功了，非常感谢，另外想问一下您有没有python容器下目录结构解析的相关文档？或者不使用jupyter进行测试的测试文档？

1. 建议去FATE相关微信群里问问。
2. 有，https://github.com/FederatedAI/KubeFATE/tree/develop-1.10.0/docker-deploy, 看怎么测的 test_hetero_lr_job_conf.json
